import traceback


def a():
    return 1/0

def b():
    a()


def main():
    try:
        b()
    except:
        print('오류가 발생했습니다.')
        print(traceback.format_exc())

main()